# Exercici 2

Crea una funció que et generi un quadrat NxN de nombres aleatoris entre el 0 i el 100.

Que bien que en el ejercicio 1 practiqué los placeholders. Puedo hacer una de nxn entre 0 y 1 y multiplicar todos los números por 100. 


In [2]:
import numpy as np

In [4]:
def cuadradoAleatorio (n = 2):
    if type(n) is not int:
        print("No has mandado a cuadradoAleatorio un número así que no esperes que funcione bien")
        return
    return np.random.random((n,n)) * 100
    

In [5]:
print(cuadradoAleatorio(4))

[[10.74595872 16.20767913 65.66748636 23.8899696 ]
 [79.32119537 70.94595233 24.53780081 31.67755793]
 [37.68088239 62.25062897 56.41935191 61.28823449]
 [34.49296676 88.43522187 34.63973555 69.40415452]]


Tres horas para hacer el anterior y este lo saco en 10 minutos. Ni tan siquiera he tenido problema en multiplicar por un escalar. 