# Exercici 3

Crea una funció que donada una taula de dues dimensions, et calculi els totals per fila i els totals per columna.

Primero vamos a ver que le pasamos un array de 2 dimensiones. Para hacer eso me baso en ejrecios anteriores. Después veo que la misma propiedad de sum tiene capacidad de ir por columna. https://numpy.org/doc/stable/reference/generated/numpy.sum.html

In [2]:
import numpy as np

In [16]:
a = np.array([(1,2,3), (4,5,6)])  
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
b = np.random.random((5,3))

In [22]:
def sumaPorFilasYcolumnas (array):
    if type(array) is not np.ndarray:
        print("Lo que has mandado no es ni tan siquiera un Array")
        return
    elif array.ndim != 2:
        print("El array no tiene 2 y solo 2 dimensiones")
        return
    print("La suma de las columnas es la siguiente:")
    print(array.sum(axis=0))
    print("La suma de las filas es la siguiente:")
    print(array.sum(axis=1))

In [24]:
sumaPorFilasYcolumnas(a)
sumaPorFilasYcolumnas(arr)
sumaPorFilasYcolumnas(b)

La suma de las columnas es la siguiente:
[5 7 9]
La suma de las filas es la siguiente:
[ 6 15]
La suma de las columnas es la siguiente:
[ 6  8 10 12]
La suma de las filas es la siguiente:
[10 26]
La suma de las columnas es la siguiente:
[3.04959306 1.81343023 1.2335018 ]
La suma de las filas es la siguiente:
[1.07966842 1.81434868 0.75898184 1.25829487 1.18523128]
