# Exercici 1

Crea una funció que donat un Array d’una dimensió, et faci un resum estadístic bàsic de les dades. Si detecta que l’array té més d’una dimensió, ha de mostrar un missatge d’error.

In [2]:
import numpy as np

In [3]:
arr = np.array([1, 2, 3, 4, 5])

print(arr)


[1 2 3 4 5]


Como esto se me escapa voy a ir tomando apuntes poco a poco y al final de este notebook estará la solución, pero voy construyéndola de a poco. Primero voy a hacer una funcion que te diga si un algo es un array de dimension 1 o no. Estoy usando esto: https://www.w3schools.com/python/numpy/numpy_creating_arrays.asp (donde pone check number of dimensions) y que usa ndim

In [4]:
a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim) 

0
1
2
3


In [13]:
def arrayDeUnaDimension(prueba):
    if type(prueba) is not np.ndarray:
        print("Lo que has mandado no es ni tan siquiera un Array")
    elif prueba.ndim != 1:
        print("El array no tiene una y solo 1 dimension")
    else:
        print("El array es de una dimension")

arrayDeUnaDimension(a)
arrayDeUnaDimension(b)
arrayDeUnaDimension(c)
arrayDeUnaDimension(d)
arrayDeUnaDimension("Charquicán")
arrayDeUnaDimension(44)
arrayDeUnaDimension((44,33,22))

El array no tiene una y solo 1 dimension
El array es de una dimension
El array no tiene una y solo 1 dimension
El array no tiene una y solo 1 dimension
Lo que has mandado no es ni tan siquiera un Array
Lo que has mandado no es ni tan siquiera un Array
Lo que has mandado no es ni tan siquiera un Array


He utilizado de base elementos del ejercicio 5 anterior de la prueba anterior para revisar también la clase de objeto. Al haber estado trabajando muchas veces con lenguajes fuertemente tipados como C o Java me pone nervioso que puedas mandar a una función CUALQUIER cosa así como así. 

https://github.com/d-prieto/estructures_control/blob/main/S03%20T03%20Exercici%205.ipynb (de aquí lo saqué y tuneé)

Lo siguiente va a ser revisar las opciones que tenemos para tratar este array. Según la cheatsheet ( http://datacamp-community-prod.s3.amazonaws.com/da466534-51fe-4c6d-b0cb-154f4782eb54) tenemos estas opciones

a.sum() Array-wise sum
a.min() Array-wise minimum value
a.max() máximo (si le quieres decir el eje pones axis = 0,1 o 2)
b.cumsum(axis) suma acumulativa de elementos
a.mean() media
b.median() mediana
a.corrcoef() coeficiente de corelación
np.std(a) desviación típica

Así que vamos a ello:


In [35]:
def estadisticasArray1D(array):
    if type(array) is not np.ndarray:
        print("Lo que has mandado no es ni tan siquiera un Array")
        return
    elif array.ndim != 1:
        print("El array no tiene una y solo 1 dimension")
        return
    print("Has mandado este array de 1 dimensión: ")
    print(array)
    print("Y sus atributos estadísticos son:")
    print("Suma")
    print(array.sum())
    print("Mínimo")
    print(array.min())
    print("Máximo")
    print(array.max())
    print("media")
    print(array.mean())
    print("Suma acumulada")
    print(array.cumsum())

    print("Mediana")
    print(np.median(array))
    print("Coeficiente de correlación:")
    print(np.corrcoef(array))
    print("Desviacion típica")
    print(np.std(array))
    print("-------------------------")
    
estadisticasArray1D(b)    

Has mandado este array de 1 dimensión: 
[1 2 3 4 5]
Y sus atributos estadísticos son:
Suma
15
Mínimo
1
Máximo
5
media
3.0
Suma acumulada
[ 1  3  6 10 15]
Mediana
3.0
Coeficiente de correlación:
1.0
Desviacion típica
1.4142135623730951
-------------------------


Por lo visto da error al encontrar la mediana, en el ejemplo sale un array de 2 dimensiones así que a lo mejor es eso. También el coeficiente de correlación.

```python
    #Esto da error porque razones
   # print("Mediana")
   # print(array.median())
   #  print("Coeficiente de correlación:")
    # print(array.corrcoef())
    #Esto da error porque razones

```

Encontrado. Las cheatsheets están mal. No es array.median o array.corrcoef sino np.median(array) o np.corrcoef(array)

## Extra placeholders

Para probar los rellenadores voy a probarlos y mandarlos por la funciòn tan flama que me he hecho antes

```python
    np.zeros((3,4))                Create an array of zeros
    np.ones((2,3,4),dtype=np.int16) Create an array of ones
   d = np.arange(10,25,5)         Create an array of evenly   spaced values (step value) 
   np.linspace(0,2,9)             Create an array of evenly   spaced values (number of samples)
    e = np.full((2,2),7)           Create a constant array    
   f = np.eye(2)                  Create a 2X2 identity matrix
    np.random.random((2,2))        Create an array with random values
    np.empty((3,2))                Create an empty array
```

In [39]:
zeros = np.zeros((1,5))
print(zeros)
zeros = np.zeros(5)
estadisticasArray1D(zeros)  
ones = np.ones(23)
estadisticasArray1D(ones)
aranged = np.arange(10,25,5)
estadisticasArray1D(aranged) 
arangedNumberOfValues =np.linspace(0,2,9)
estadisticasArray1D(arangedNumberOfValues)
constante = np.full(33,7) 
estadisticasArray1D(constante)
estocastico = np.random.random(10)
estadisticasArray1D(estocastico)

[[0. 0. 0. 0. 0.]]
Has mandado este array de 1 dimensión: 
[0. 0. 0. 0. 0.]
Y sus atributos estadísticos son:
Suma
0.0
Mínimo
0.0
Máximo
0.0
media
0.0
Suma acumulada
[0. 0. 0. 0. 0.]
Mediana
0.0
Coeficiente de correlación:
nan
Desviacion típica
0.0
-------------------------
Has mandado este array de 1 dimensión: 
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
Y sus atributos estadísticos son:
Suma
23.0
Mínimo
1.0
Máximo
1.0
media
1.0
Suma acumulada
[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.
 19. 20. 21. 22. 23.]
Mediana
1.0
Coeficiente de correlación:
nan
Desviacion típica
0.0
-------------------------
Has mandado este array de 1 dimensión: 
[10 15 20]
Y sus atributos estadísticos son:
Suma
45
Mínimo
10
Máximo
20
media
15.0
Suma acumulada
[10 25 45]
Mediana
15.0
Coeficiente de correlación:
1.0
Desviacion típica
4.08248290463863
-------------------------
Has mandado este array de 1 dimensión: 
[0.   0.25 0.5  0.75 1.   1.25 1.5  1.75

Importante, cuando creas un array/matriz de estas, para 1 dimensiòn hay que poner solo el nùmero de elementos. Para màs dimensiones sì hay que indicar la tupla de la forma